#!/bin/sh

echo "Running static analysis"

./gradlew ktlint detekt lintRelease apiCheck verifyReleaseResources verifyPaparazziDebug

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis ran successfully."
    exit 0
else
    echo "Static analysis failed."
    exit 1
fi
