import groovy.text.SimpleTemplateEngine
import java.util.stream.Collectors

apply from: configs.androidLibrary

apply plugin: 'checkstyle'
apply plugin: "org.jetbrains.kotlin.plugin.parcelize"
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'

dependencies {
    implementation libs.androidx.appCompat
    implementation libs.androidx.core
    implementation libs.kotlin.serialization

    testImplementation testLibs.junit
    testImplementation testLibs.kotlin.test
    testImplementation testLibs.mockito.inline
    testImplementation testLibs.mockito.kotlin
    testImplementation testLibs.robolectric
    testImplementation testLibs.truth
}

android {
    buildFeatures {
        buildConfig true
    }

    testOptions {
        animationsDisabled = true
        unitTests {
            returnDefaultValues = true
            includeAndroidResources = true
        }
    }
}

abstract class GenerateHtmlClass extends DefaultTask {
    @InputFile
    abstract RegularFileProperty getTemplateFile()

    @InputFile
    abstract RegularFileProperty getHtmlFile()

    @Input
    abstract Property<String> getPackageName()

    @OutputDirectory
    abstract DirectoryProperty getOutputDirectory()

    @TaskAction
    void generate() {
        def html = htmlFile.get().asFile.readLines()
                .stream()
                .collect(Collectors.joining("\n"))

        def engine = new SimpleTemplateEngine()
        def src = engine.createTemplate(templateFile.get().asFile.text).make([
                "htmlContent": html,
                "packageName": packageName.get()
        ])

        def packagePath = packageName.get().replaceAll('\\.', '/')
        def outDir = outputDirectory.dir(packagePath).get().asFile
        outDir.mkdirs()
        new File(outDir, "HCaptchaHtml.kt").write(src.toString())
    }
}

// Generate the HTML class for hCaptcha
def generateHtmlClass = tasks.register("generateJavaClassFromStaticHtml", GenerateHtmlClass) {
    group 'Generate'
    description "Generate HTML java class"

    templateFile = project.layout.projectDirectory.file("src/main/html/HCaptchaHtml.java.tml")
    htmlFile = project.layout.projectDirectory.file("src/main/html/hcaptcha.html")
    packageName = "com.stripe.hcaptcha"
    outputDirectory = project.layout.buildDirectory.dir("generated/source/hcaptcha/main")
}

androidComponents {
    onVariants(selector().all()) { variant ->
        variant.sources.kotlin.addGeneratedSourceDirectory(generateHtmlClass) {
            it.outputDirectory
        }
    }
}

ext {
    artifactId = "hcaptcha"
    artifactName = "hcaptcha"
    artifactDescrption = "The hcaptcha module of Stripe Payment Android SDK"
}

apply from: "${rootDir}/deploy/deploy.gradle"
