import groovy.text.SimpleTemplateEngine
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

apply from: configs.androidLibrary

apply plugin: 'checkstyle'
apply plugin: "org.jetbrains.kotlin.plugin.parcelize"
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'

dependencies {
    implementation libs.androidx.appCompat
    implementation libs.androidx.core
    implementation libs.kotlin.serialization

    testImplementation testLibs.junit
    testImplementation testLibs.kotlin.test
    testImplementation testLibs.mockito.inline
    testImplementation testLibs.mockito.kotlin
    testImplementation testLibs.robolectric
    testImplementation testLibs.truth
}

android {
    buildFeatures {
        buildConfig true
    }

    testOptions {
        animationsDisabled = true
        unitTests {
            returnDefaultValues = true
            includeAndroidResources = true
        }
    }
}

abstract class GenerateJavaClassFromStaticHtml extends DefaultTask {
    @InputFile abstract RegularFileProperty getTemplateFile()
    @InputFile abstract RegularFileProperty getHtmlFile()
    @Input abstract Property<String> getPackageName()
    @OutputDirectory abstract DirectoryProperty getOutputDir()

    @TaskAction
    void generate() {
        def html = htmlFile.get().asFile.readLines().join("\n")
        def engine = new SimpleTemplateEngine()
        def src = engine.createTemplate(templateFile.get().asFile.text).make([
                "htmlContent": html,
                "packageName": packageName.get()
        ])

        def packagePath = packageName.get().replace('.', '/')
        def outDir = new File(outputDir.get().asFile, packagePath)
        outDir.mkdirs()
        new File(outDir, "HCaptchaHtml.kt").write(src.toString())
    }
}

def generateHtmlClass = tasks.register("generateJavaClassFromStaticHtml", GenerateJavaClassFromStaticHtml) {
    group 'Generate'
    description "Generate HTML java class"
    templateFile.set(project.layout.projectDirectory.file("src/main/html/HCaptchaHtml.java.tml"))
    htmlFile.set(project.layout.projectDirectory.file("src/main/html/hcaptcha.html"))
    packageName.set("com.stripe.hcaptcha")
    outputDir.set(project.layout.buildDirectory.dir("generated/source/hcaptcha/main"))
}

androidComponents.onVariants(androidComponents.selector().all()) { variant ->
    variant.sources.kotlin?.addGeneratedSourceDirectory(generateHtmlClass) { task -> task.outputDir }
}

ext {
    artifactId = "hcaptcha"
    artifactName = "hcaptcha"
    artifactDescrption = "The hcaptcha module of Stripe Payment Android SDK"
}

apply from: "${rootDir}/deploy/deploy.gradle"
