---
format_version: '11'
default_step_lib_source: 'https://github.com/bitrise-io/bitrise-steplib.git'
project_type: android
trigger_map:
  - push_branch: 'master'
    pipeline: main-trigger-pipeline
  - pull_request_source_branch: 'carlosmuvi/maestro-record'
    workflow: maestro-financial-connections
app:
  envs:
    - GRADLE_OPTS: -Dkotlin.incremental=false

pipelines:
  main-trigger-pipeline:
    stages:
      - stage-trigger-run-all: { }

stages:
  stage-trigger-run-all:
    workflows:
      - check: { }
      - test: { }
      - run-instrumentation-tests: { }

workflows:
  check:
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          inputs:
            - content: ./gradlew ktlint detekt lintRelease apiCheck
  test:
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          title: Restore gradle.properties
          inputs:
            - content: mkdir -p ~/.gradle ; cp .bitrise/ci-gradle.properties ~/.gradle/gradle.properties
      - script@1:
          inputs:
            - content: ./gradlew testDebugUnitTest verifyPaparazziDebug -x :stripe-test-e2e:testDebugUnitTest
  maestro-financial-connections:
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - avd-manager@1: { }
      - wait-for-android-emulator@1: { }
      - script-runner@0:
          title: Execute Maestro tests
          inputs:
            - file_path: ./scripts/execute_maestro_tests.sh
      - slack@3:
          is_always_run: true
          inputs:
            - webhook_url: $WEBHOOK_SLACK_CARLOSMUVI_MAESTRO
            - webhook_url_on_error: $WEBHOOK_SLACK_CARLOSMUVI_MAESTRO
      - script@1:
          title: Notify failure endpoint
          inputs:
            - content: |
                #!/usr/bin/env bash
                set -e
                set -o pipefail
                set -x
                
                ruby ./scripts/notify_failure_endpoint.rb \
                $SDK_FAILURE_NOTIFICATION_ENDPOINT \
                $SDK_FAILURE_NOTIFICATION_ENDPOINT_HMAC_KEY \
                $BITRISE_BUILD_URL \
                RUN_BANKCON_MOBILE
          is_always_run: true
          run_if: ".IsBuildFailed"
      - custom-test-results-export@0:
          inputs:
            - search_pattern: '*/maestroReport.xml'
            - test_name: Maestro tests
      - deploy-to-bitrise-io@2: { }
  maestro-paymentsheet:
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - avd-manager@1: { }
      - wait-for-android-emulator@1: { }
      - script-runner@0:
          title: Execute Maestro tests
          inputs:
            - file_path: ./scripts/execute_maestro_paymentsheet_tests.sh
      - slack@3:
          is_always_run: true
          inputs:
            - webhook_url: $WEBHOOK_SLACK_ELEMENTS_MAESTRO
            - webhook_url_on_error: $WEBHOOK_SLACK_ELEMENTS_MAESTRO
      - custom-test-results-export@0:
          inputs:
            - search_pattern: '*/maestroReport.xml'
            - test_name: Maestro tests
      - deploy-to-bitrise-io@2: { }
  run-instrumentation-tests:
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - avd-manager@1: { }
      - wait-for-android-emulator@1: { }
      - script-runner@0:
          title: Execute instrumentation tests
          inputs:
            - file_path: ./scripts/execute_instrumentation_tests.sh
  prepare_all:
    steps:
      - activate-ssh-key@4:
          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
      - git-clone@8: { }
      - cache-pull@2: { }
      - script@1:
          inputs:
            - content: mkdir -p ~/.gradle ; cp .bitrise/ci-gradle.properties ~/.gradle/gradle.properties
      - script@1:
          inputs:
            - content: echo "STRIPE_EXAMPLE_BACKEND_URL=$STRIPE_EXAMPLE_BACKEND_URL" >> ~/.gradle/gradle.properties; echo "STRIPE_EXAMPLE_PUBLISHABLE_KEY=$STRIPE_EXAMPLE_PUBLISHABLE_KEY" >> ~/.gradle/gradle.properties
  conclude_all:
    steps:
      - script-runner@0:
          is_always_run: true
          title: Copy test results to tmp
          inputs:
            - file_path: ./scripts/copy_test_results_to_tmp.sh
      - deploy-to-bitrise-io@2:
          inputs:
            - notify_user_groups: none
            - is_compress: "true"
            - deploy_path: /tmp/test_results
            - is_enable_public_page: "false"
          title: Deploy test results artifacts
      - cache-push@2: { }
meta:
  bitrise.io:
    stack: linux-docker-android-20.04
    machine_type_id: elite
