---
format_version: '11'
default_step_lib_source: 'https://github.com/bitrise-io/bitrise-steplib.git'
project_type: android
trigger_map:
  - push_branch: 'master'
    pipeline: main-trigger-pipeline
  - pull_request_source_branch: '*'
    pipeline: main-trigger-pipeline
app:
  envs:
    - GRADLE_OPTS: -Dkotlin.incremental=false

pipelines:
  main-trigger-pipeline:
    stages:
      - stage-trigger-run-all: { }
  pipeline-connect-e2e-debug-tests:
    stages:
      - stage-run-connect-e2e-tests: { }
      # TODO: notify failure
  pipeline-connections-e2e-debug-tests:
    stages:
      - stage-build-connections-debug: { }
      - stage-run-connections-e2e-tests: { }
      - stage-notify-connections-e2e-failure: { }
  pipeline-connections-e2e-release-tests:
    stages:
      - stage-build-connections-release: { }
      - stage-run-connections-e2e-tests: { }
      - stage-notify-connections-e2e-failure: { }
stages:
  stage-trigger-run-all:
    workflows:
      - check: { }
      - test: { }
      - run-instrumentation-tests: { }
      - run-paymentsheet-instrumentation-tests: { }
      - run-example-instrumentation-tests: { }
      - run-financial-connections-instrumentation-tests: { }
      - run-connections-e2e-payments-tests-on-push: { }
      - run-connections-e2e-token-tests-on-push: { }
      - run-connections-e2e-data-tests-on-push: { }
      - run-paymentsheet-end-to-end-tests: { }
      - run-crypto-onramp-example-e2e-tests: { }
      - check-dependencies: { }
  stage-run-connect-e2e-tests:
    workflows:
      - run-connect-e2e-tests: { }
  stage-build-connections-debug:
    workflows:
      - build-connections-debug: { }
  stage-build-connections-release:
    workflows:
      - build-connections-release: { }
  stage-run-connections-e2e-tests:
    workflows:
      - run-connections-e2e-payments-tests: { }
      - run-connections-e2e-data-tests: { }
      - run-connections-e2e-token-tests: { }
      - run-connections-e2e-livemode-tests: { }
  stage-notify-connections-e2e-failure:
    should_always_run: true
    workflows:
      - notify-connections-e2e-failure: { }
workflows:
  _install_java:
    steps:
      - script@1:
          title: Install Java via Direct Download
          inputs:
            - content: |-
                #!/bin/bash
                set -eo pipefail

                # Default to Java 25 if not specified
                JAVA_VERSION=${JAVA_VERSION:-25}

                # Determine architecture
                ARCH=$(uname -m)
                if [ "$ARCH" = "x86_64" ]; then
                  ARCH="x64"
                elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
                  ARCH="aarch64"
                fi

                # Determine OS (Adoptium uses "mac" for macOS, not "darwin")
                OS=$(uname -s)
                if [ "$OS" = "Darwin" ]; then
                  OS="mac"
                else
                  OS=$(echo "$OS" | tr '[:upper:]' '[:lower:]')
                fi

                # Download Java from Adoptium (Eclipse Temurin)
                JAVA_DIR="$HOME/java-${JAVA_VERSION}"

                if [ ! -d "$JAVA_DIR" ]; then
                  echo "Downloading Java ${JAVA_VERSION} for ${OS}-${ARCH}..."

                  # Construct download URL for Adoptium
                  DOWNLOAD_URL="https://api.adoptium.net/v3/binary/latest/${JAVA_VERSION}/ga/${OS}/${ARCH}/jdk/hotspot/normal/eclipse"

                  mkdir -p "$JAVA_DIR"

                  # Download with retries
                  MAX_RETRIES=3
                  RETRY_COUNT=0
                  DOWNLOAD_SUCCESS=false

                  while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
                    if curl -fSL --connect-timeout 30 --max-time 600 --retry 3 --retry-delay 5 \
                         "$DOWNLOAD_URL" -o "/tmp/java-${JAVA_VERSION}.tar.gz"; then
                      DOWNLOAD_SUCCESS=true
                      break
                    else
                      RETRY_COUNT=$((RETRY_COUNT + 1))
                      if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                        echo "Download failed, retrying in $((RETRY_COUNT * 5)) seconds... (attempt $((RETRY_COUNT + 1))/$MAX_RETRIES)"
                        sleep $((RETRY_COUNT * 5))
                      fi
                    fi
                  done

                  if [ "$DOWNLOAD_SUCCESS" = false ]; then
                    echo "Failed to download Java after $MAX_RETRIES attempts"
                    exit 1
                  fi

                  # Verify download
                  if [ ! -f "/tmp/java-${JAVA_VERSION}.tar.gz" ]; then
                    echo "Downloaded file not found"
                    exit 1
                  fi

                  # Extract to Java directory
                  echo "Extracting Java to $JAVA_DIR..."
                  if ! tar -xzf "/tmp/java-${JAVA_VERSION}.tar.gz" -C "$JAVA_DIR" --strip-components=1; then
                    echo "Extraction failed, trying without strip-components..."
                    rm -rf "$JAVA_DIR"
                    mkdir -p "$JAVA_DIR"
                    tar -xzf "/tmp/java-${JAVA_VERSION}.tar.gz" -C "$JAVA_DIR"

                    # Find the actual JDK directory and move contents up
                    JDK_DIR=$(find "$JAVA_DIR" -maxdepth 1 -type d -name "jdk*" -o -name "temurin*" | head -1)
                    if [ -n "$JDK_DIR" ]; then
                      echo "Moving contents from $JDK_DIR to $JAVA_DIR"
                      mv "$JDK_DIR"/* "$JAVA_DIR"/
                      rmdir "$JDK_DIR"
                    fi
                  fi

                  rm "/tmp/java-${JAVA_VERSION}.tar.gz"

                  # On macOS, the JDK is in Contents/Home subdirectory
                  if [ -d "$JAVA_DIR/Contents/Home" ]; then
                    JAVA_HOME="$JAVA_DIR/Contents/Home"
                  else
                    JAVA_HOME="$JAVA_DIR"
                  fi

                  # Verify Java was extracted correctly
                  if [ ! -f "$JAVA_HOME/bin/java" ]; then
                    echo "Java binary not found at $JAVA_HOME/bin/java. Directory contents:"
                    ls -la "$JAVA_DIR"
                    if [ -d "$JAVA_DIR/Contents" ]; then
                      echo "Contents directory:"
                      ls -la "$JAVA_DIR/Contents"
                    fi
                    exit 1
                  fi
                else
                  echo "Java ${JAVA_VERSION} already installed at $JAVA_DIR"
                  # On macOS, the JDK is in Contents/Home subdirectory
                  if [ -d "$JAVA_DIR/Contents/Home" ]; then
                    JAVA_HOME="$JAVA_DIR/Contents/Home"
                  else
                    JAVA_HOME="$JAVA_DIR"
                  fi
                fi

                # Export for subsequent Bitrise steps
                envman add --key JAVA_HOME --value "$JAVA_HOME"
                envman add --key PATH --value "$JAVA_HOME/bin:$PATH"

                # Verify
                "$JAVA_HOME/bin/java" -version
  check:
    envs:
      - JAVA_VERSION: 22
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          timeout: 1200
          inputs:
            - content: ./gradlew ktlint detekt lintRelease apiCheck verifyReleaseResources
  test:
    envs:
      - opts:
          is_expand: false
        NEEDS_ROBOLECTRIC: true
      - INCLUDE_PAPARAZZI_ON_FAILURE: true
    meta:
      bitrise.io:
        stack: osx-xcode-16.2.x    # Specify Mac stack just for this workflow
        machine_type_id: g2.mac.4large # Appropriate Mac instance
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          timeout: 1200
          inputs:
            - content: ./scripts/retry.sh 3 ./gradlew testDebugUnitTest verifyPaparazziDebug -x :stripe-test-e2e:testDebugUnitTest --continue
  build-connect-debug:
    envs:
      - BUILD_VARIANT: debug
    before_run:
      - _build-connect
  _build-connect:
    before_run:
      - prepare_all
    steps:
      - android-build@1:
          inputs:
            - module: connect-example
            - variant: $BUILD_VARIANT
            - build_type: apk
      - deploy-to-bitrise-io@2:
          inputs:
            - pipeline_intermediate_files: "$BITRISE_APK_PATH:BITRISE_APK_PATH"
  build-connections-debug:
    envs:
      - BUILD_VARIANT: debug
    before_run:
      - _build-connections
  build-connections-release:
    envs:
      - BUILD_VARIANT: release
    before_run:
      - _build-connections
  _build-connections:
    before_run:
      - prepare_all
    steps:
      - android-build@1:
          inputs:
            - arguments: -PSTRIPE_FINANCIAL_CONNECTIONS_EXAMPLE_BACKEND_URL=$STRIPE_FINANCIAL_CONNECTIONS_EXAMPLE_BACKEND_URL
            - module: financial-connections-example
            - variant: $BUILD_VARIANT
            - build_type: apk
      - deploy-to-bitrise-io@2:
          inputs:
            - pipeline_intermediate_files: "$BITRISE_APK_PATH:BITRISE_APK_PATH"
  run-connect-e2e-tests:
    envs:
      - MAESTRO_TAGS: all
    before_run:
      - _run-connect-e2e-tests
  run-connections-e2e-payments-tests:
    envs:
      - MAESTRO_TAGS: testmode-payments
    before_run:
      - _run-connections-e2e-tests
  run-connections-e2e-data-tests:
    envs:
      - MAESTRO_TAGS: testmode-data
    before_run:
      - _run-connections-e2e-tests
  run-connections-e2e-token-tests:
    envs:
      - MAESTRO_TAGS: testmode-token
    before_run:
      - _run-connections-e2e-tests
  run-connections-e2e-payments-tests-on-push:
    envs:
      - MAESTRO_TAGS: testmode-payments
      - BUILD_VARIANT: release
    before_run:
      - _build-connections
      - _run-connections-e2e-tests
    meta:
      bitrise.io:
        stack: linux-docker-android-22.04
        machine_type_id: g2.linux.x-large
  run-connections-e2e-data-tests-on-push:
    envs:
      - MAESTRO_TAGS: testmode-data
      - BUILD_VARIANT: release
    before_run:
      - _build-connections
      - _run-connections-e2e-tests
    meta:
      bitrise.io:
        stack: linux-docker-android-22.04
        machine_type_id: g2.linux.x-large
  run-connections-e2e-token-tests-on-push:
    envs:
      - MAESTRO_TAGS: testmode-token
      - BUILD_VARIANT: release
    before_run:
      - _build-connections
      - _run-connections-e2e-tests
    meta:
      bitrise.io:
        stack: linux-docker-android-22.04
        machine_type_id: g2.linux.x-large
  run-connections-e2e-livemode-tests:
    envs:
      - MAESTRO_TAGS: livemode-data
    before_run:
      - _run-connections-e2e-tests
  _run-connect-e2e-tests:
    before_run:
      - build-connect-debug
      - start_connections_emulator
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - wait-for-android-emulator@1:
          inputs:
            - boot_timeout: 600
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: .*
      - script@1:
          title: Execute Maestro tests
          inputs:
            - content: |-
                #!/usr/bin/env bash
                bash ./scripts/execute_maestro_tests.sh -m connect -t $MAESTRO_TAGS
  _run-connections-e2e-tests:
    before_run:
      - start_connections_emulator
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - wait-for-android-emulator@1:
          inputs:
            - boot_timeout: 600
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: .*
      - script@1:
          title: Execute Maestro tests
          inputs:
            - content: |-
                #!/usr/bin/env bash
                bash ./scripts/execute_maestro_tests.sh -m financial-connections -t $MAESTRO_TAGS
  notify-connections-e2e-failure:
    steps:
      # Notify all executions.
      - slack@4:
          inputs:
            - webhook_url: $WEBHOOK_SLACK_CONNECTIONS_MOBILE
            - webhook_url_on_error: $WEBHOOK_SLACK_CONNECTIONS_MOBILE
      # Notify failures.
      - slack@4:
          run_if: '{{ getenv "BITRISEIO_PIPELINE_BUILD_STATUS" | eq "failed" }}'
          inputs:
            - webhook_url: $WEBHOOK_SLACK_CUX_BOTS
            - webhook_url_on_error: $WEBHOOK_SLACK_CUX_BOTS
  run-instrumentation-tests:
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          title: Execute instrumentation tests
          timeout: 1200
          inputs:
            - content: ./gradlew -Pandroid.experimental.androidTest.numManagedDeviceShards=1 pixel2api33DebugAndroidTest -x :paymentsheet-example:pixel2api33BaseDebugAndroidTest -x :paymentsheet:pixel2api33DebugAndroidTest -x :example:pixel2api33DebugAndroidTest -x :financial-connections:pixel2api33DebugAndroidTest -x :financial-connections-example:pixel2api33DebugAndroidTest -x :camera-core:pixel2api33DebugAndroidTest -x :crypto-onramp-example:pixel2api33DebugAndroidTest
  run-paymentsheet-instrumentation-tests:
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          title: Execute instrumentation tests
          timeout: 1200
          inputs:
            - content: ./scripts/retry.sh 3 ./gradlew -Pandroid.experimental.androidTest.numManagedDeviceShards=6 -Pandroid.experimental.testOptions.managedDevices.maxConcurrentDevices=6 :paymentsheet:pixel2api33DebugAndroidTest
    meta:
      bitrise.io:
        stack: linux-docker-android-22.04
        machine_type_id: g2.linux.x-large
  run-example-instrumentation-tests:
    before_run:
      - start_emulator
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          title: Assemble Instrumentation tests
          timeout: 600
          inputs:
            - content: ./gradlew :example:assembleAndroidTest
      - wait-for-android-emulator@1:
          inputs:
            - boot_timeout: 600
      - script@1:
          title: Execute instrumentation tests
          timeout: 1200
          inputs:
            - content: ./scripts/retry.sh 3 ./gradlew :example:connectedAndroidTest
  run-financial-connections-instrumentation-tests:
    before_run:
      - start_emulator
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          title: Assemble Instrumentation tests
          timeout: 600
          inputs:
            - content: ./gradlew :financial-connections:assembleAndroidTest :financial-connections-example:assembleAndroidTest
      - wait-for-android-emulator@1:
          inputs:
            - boot_timeout: 600
      - script@1:
          title: Execute instrumentation tests
          timeout: 1200
          inputs:
            - content: ./gradlew :financial-connections:connectedAndroidTest :financial-connections-example:connectedAndroidTest
  run-paymentsheet-end-to-end-tests:
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          timeout: 1200
          inputs:
            - content: ./gradlew :paymentsheet-example:assembleBaseDebugAndroidTest :paymentsheet-example:assembleBaseDebug -PIS_BROWSERSTACK_BUILD=true -PSTRIPE_PAYMENTSHEET_EXAMPLE_SENTRY_DSN=$STRIPE_PAYMENTSHEET_EXAMPLE_SENTRY_DSN
      - script@1:
          timeout: 120
          inputs:
            - content: pip3 install requests_toolbelt requests
      - script@1:
          timeout: 2400
          inputs:
            - content: python3 scripts/browserstack.py --test --apk paymentsheet-example/build/outputs/apk/base/debug/paymentsheet-example-base-debug.apk --espresso paymentsheet-example/build/outputs/apk/androidTest/base/debug/paymentsheet-example-base-debug-androidTest.apk --num-retries 2
  run-crypto-onramp-example-e2e-tests:
    before_run:
      - start_emulator
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          timeout: 1200
          inputs:
            - content: ./gradlew :crypto-onramp-example:assembleDebug :crypto-onramp-example:assembleDebugAndroidTest
      - wait-for-android-emulator@1:
          inputs:
            - boot_timeout: 600
      - script@1:
          title: Run Crypto Onramp Example E2E Tests
          timeout: 1200
          inputs:
            - content: ./gradlew :crypto-onramp-example:connectedDebugAndroidTest
  check-dependencies:
    envs:
      - INCLUDE_DEPENDENCIES_ON_FAILURE: true
    before_run:
      - prepare_all
    after_run:
      - conclude_all
    steps:
      - script@1:
          inputs:
            - content: asdf install ruby 3.2.4
      - script@1:
          inputs:
            - content: ruby scripts/dependencies/update_transitive_dependencies.rb
      - script@1:
          inputs:
            - content: ruby scripts/dependencies/check_transitive_dependencies.rb
  start_connections_emulator:
    steps:
      - avd-manager@2:
          inputs:
            - profile: "pixel_6"
            - abi: "x86_64"
            - api_level: 33
            - tag: "google_apis"
            - start_command_flags: >
                -camera-back none
                -camera-front none
                -netdelay none
                -netspeed full
                -memory 4096
                -no-snapshot
                -no-audio
                -no-window
  start_emulator:
    steps:
      - avd-manager@2:
          inputs:
            - profile: "pixel_6"
            - abi: "x86_64"
            - api_level: 33
            - tag: "google_apis"
            - start_command_flags: >
               -camera-back none
               -camera-front none
               -netdelay none
               -netspeed full
               -memory 4096
               -no-snapshot
               -no-audio
               -no-window
  start_screenshot_emulator:
    steps:
      - avd-manager@2:
          inputs:
            - profile: "Nexus 6"
            - abi: "x86_64"
            - api_level: 28
            - start_command_flags: >
                -camera-back none
                -camera-front none
                -netdelay none
                -netspeed full
                -memory 2048
                -no-snapshot
                -no-audio
                -no-window
                -no-snapshot-save
                -gpu swiftshader_indirect
                -no-boot-anim
  prepare_all:
    before_run:
      - _install_java
    steps:
      - activate-ssh-key@4:
          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
      - git-clone@8: { }
      - restore-gradle-configuration-cache@1: { }
      - restore-gradle-cache@2: { }
      - script@1:
          inputs:
            - content: mkdir -p ~/.gradle ; cp .bitrise/ci-gradle.properties ~/.gradle/gradle.properties
      - script@1:
          inputs:
            - content: echo "STRIPE_EXAMPLE_BACKEND_URL=$STRIPE_EXAMPLE_BACKEND_URL" >> ~/.gradle/gradle.properties; echo "STRIPE_EXAMPLE_PUBLISHABLE_KEY=$STRIPE_EXAMPLE_PUBLISHABLE_KEY" >> ~/.gradle/gradle.properties
      - activate-build-cache-for-gradle:
          inputs:
            - push: 'true'
            - validation_level: warning
  conclude_all:
    steps:
      - script-runner@0:
          is_always_run: true
          title: Copy test results to tmp
          inputs:
            - file_path: ./scripts/copy_test_results_to_tmp.sh
      - deploy-to-bitrise-io@2:
          inputs:
            - notify_user_groups: none
            - is_compress: "true"
            - deploy_path: /tmp/test_results
            - is_enable_public_page: "false"
          title: Deploy test results artifacts
      - save-gradle-configuration-cache@1: { }
      - save-gradle-cache@1: { }
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: g2.linux.medium
