name: "Stripe Setup"
description: "Sets up the GitHub Actions Workflow"

runs:
  using: "composite"
  steps:
    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      shell: bash
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '25'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
