name: "Stripe Setup"
description: "Sets up the GitHub Actions Workflow"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
