name: "Stripe Setup"
description: "Sets up the GitHub Actions Workflow"

runs:
  using: "composite"
  steps:
    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      shell: bash
    - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
      with:
        distribution: 'temurin'
        java-version: '25'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
