blank_issues_enabled: false
contact_links:
  - name: 🤔 SDK Integration Support
    url: https://stripe.com/go/developer-chat
    about: If you're having general trouble with your Stripe integration, please reach out to us on Discord
