@startuml
'https://plantuml.com/sequence-diagram

@startuml
[ConnectionsSheet] as C


package internal {
[DefaultConnectionsSheetLauncher] as DL
[ConnectionsSheetForTokenLauncher] as TL #LightGreen
[ConnectionsSheetActivity] as A
}


C --> DL: create ( ConnectionsSheetResult )
C --> TL: createForToken ( ConnectionsSheetForTokenResult )
DL --> A: Args.Default
TL --> A: Args.ForToken

@enduml
