package com.stripe.android.crypto.onramp.example

internal const val LOGIN_EMAIL_TAG = "LoginEmailTag"
internal const val LOGIN_PASSWORD_TAG = "LoginPasswordTag"
internal const val LOGIN_LOGIN_BUTTON_TAG = "LoginLoginButtonTag"
internal const val LOGIN_REGISTER_BUTTON_TAG = "LoginRegisterButtonTag"
internal const val AUTHENTICATE_BUTTON_TAG = "AuthenticateButtonTag"
internal const val REGISTER_WALLET_BUTTON_TAG = "RegisterWalletButtonTag"
internal const val COLLECT_CARD_BUTTON_TAG = "CollectCardButtonTag"
internal const val CREATE_CRYPTO_TOKEN_BUTTON_TAG = "CreateCryptoTokenButtonTag"
internal const val CREATE_SESSION_BUTTON_TAG = "CreateSessionButtonTag"
internal const val CHECKOUT_BUTTON_TAG = "CheckoutButtonTag"
internal const val INITIALIZATION_FAILURE_ALERT_TAG = "InitializationFailureAlertTag"
internal const val INITIALIZATION_FAILURE_ALERT_TITLE_TAG = "InitializationFailureAlertTitleTag"
internal const val INITIALIZATION_FAILURE_ALERT_MESSAGE_TAG = "InitializationFailureAlertMessageTag"
internal const val SNACKBAR_TAG = "SnackbarTag"
internal const val SNACKBAR_TEXT_TAG = "SnackbarTextTag"
