package com.stripe.android.crypto.onramp.example

internal const val LOGIN_EMAIL_TAG = "LoginEmailTag"
internal const val LOGIN_PASSWORD_TAG = "LoginPasswordTag"
internal const val LOGIN_LOGIN_BUTTON_TAG = "LoginLoginButtonTag"
internal const val LOGIN_REGISTER_BUTTON_TAG = "LoginRegisterButtonTag"
internal const val AUTHENTICATE_BUTTON_TAG = "AuthenticateButtonTag"
internal const val AUTHENTICATED_OPERATIONS_TAG = "AuthenticatedOperationsTag"
internal const val SEAMLESS_SIGN_IN_NOT_ME_BUTTON_TAG = "SeamlessSignInNotMeButtonTag"
internal const val BACK_TO_SIGN_IN_BUTTON_TAG = "BackToSignInButtonTag"
internal const val REGISTER_WALLET_BUTTON_TAG = "RegisterWalletButtonTag"
internal const val COLLECT_CARD_BUTTON_TAG = "CollectCardButtonTag"
internal const val COLLECT_BANK_ACCOUNT_BUTTON_TAG = "CollectBankAccountButtonTag"
internal const val CREATE_CRYPTO_TOKEN_BUTTON_TAG = "CreateCryptoTokenButtonTag"
internal const val CREATE_SESSION_BUTTON_TAG = "CreateSessionButtonTag"
internal const val CHECKOUT_BUTTON_TAG = "CheckoutButtonTag"
internal const val LOG_OUT_BUTTON_TAG = "LogOutButtonTag"
internal const val SELECTED_PAYMENT_TYPE_TAG = "SelectedPaymentTypeTag"
internal const val SESSION_STATUS_TAG = "SessionStatusTag"
internal const val SETTLEMENT_SPEED_INSTANT_TAG = "SettlementSpeedInstantTag"
internal const val SETTLEMENT_SPEED_STANDARD_TAG = "SettlementSpeedStandardTag"
internal const val INITIALIZATION_FAILURE_ALERT_TAG = "InitializationFailureAlertTag"
internal const val INITIALIZATION_FAILURE_ALERT_TITLE_TAG = "InitializationFailureAlertTitleTag"
internal const val INITIALIZATION_FAILURE_ALERT_MESSAGE_TAG = "InitializationFailureAlertMessageTag"
internal const val SNACKBAR_TAG = "SnackbarTag"
internal const val SNACKBAR_TEXT_TAG = "SnackbarTextTag"
