#!/bin/bash

#xml is for android, strings is for iOS
FORMAT=xml

if [[ -z $(which lokalise2) ]]; then
    echo "Installing lokalise2 via homebrew..."
    brew tap lokalise/cli-2
    brew install lokalise2
fi

if [[ -z $(which recode) ]]; then
    echo "Installing recode via homebrew..."
    brew install recode
fi

# Load LOCALIZATION_DIRECTORIES & LANGUAGES variables
source localization_vars.sh

# This is the custom status ID for our project with which the localizers mark completed translations
FINAL_STATUS_ID=587


#rm -rf android/*

#strings.xml -- are android strings not assigned to a file.
#          --filter-langs $LANGUAGES \

for MODULE in "paymentsheet"  "payments-core"
do
   # List all the strings / android/$MODULE-strings.xml is generated by the localize.sh script
   cat android/$MODULE-strings.xml | gsed -E -n "s/\s*<string name=\"(.*)\">.*<\/string>/\1/pI" > android/$MODULE-localize_android_keys.txt
   sort -o android/$MODULE-localize_android_keys-sorted.txt android/$MODULE-localize_android_keys.txt

   # List all the keys in the android project.
   cat ../$MODULE/res/values/strings.xml | gsed -E -n "s/\s*<string name=\"([^ ]*)\".*>(.*)<\/string>/\1/pI" > android/$MODULE-project_keys.txt
   sort -o android/$MODULE-project_keys-sorted.txt android/$MODULE-project_keys.txt

   diff -u android/$MODULE-localize_android_keys-sorted.txt android/$MODULE-project_keys-sorted.txt  | grep -E "^\+" | sed 's/^+//g' > android/diff_keys-$MODULE.txt

   echo ""
   echo ""
   echo $MODULE
   echo "-----------------------"
   cat android/diff_keys-$MODULE.txt


done

