package com.stripe.android.paymentsheet.ui

internal enum class SheetScreen {
    LOADING,
    SELECT_SAVED_PAYMENT_METHODS,
    ADD_ANOTHER_PAYMENT_METHOD,
    ADD_FIRST_PAYMENT_METHOD,
    EDIT_PAYMENT_METHOD,
    VERTICAL_MODE,
    FORM,
    MANAGE_SAVED_PAYMENT_METHODS,
    MANAGE_ONE_SAVED_PAYMENT_METHOD,
}
