package com.stripe.android.uicore.elements

import androidx.compose.ui.autofill.ContentType

internal fun ContentType.toReadableString(): String = when (this) {
    ContentType.Username -> "username"
    ContentType.Password -> "password"
    ContentType.EmailAddress -> "emailAddress"
    ContentType.NewUsername -> "newUsername"
    ContentType.NewPassword -> "newPassword"
    ContentType.PostalAddress -> "postalAddress"
    ContentType.PostalCode -> "postalCode"
    ContentType.CreditCardNumber -> "creditCardNumber"
    ContentType.CreditCardSecurityCode -> "creditCardSecurityCode"
    ContentType.CreditCardExpirationDate -> "creditCardExpirationDate"
    ContentType.CreditCardExpirationMonth -> "creditCardExpirationMonth"
    ContentType.CreditCardExpirationYear -> "creditCardExpirationYear"
    ContentType.CreditCardExpirationDay -> "creditCardExpirationDay"
    ContentType.AddressCountry -> "addressCountry"
    ContentType.AddressRegion -> "addressRegion"
    ContentType.AddressLocality -> "addressLocality"
    ContentType.AddressStreet -> "addressStreet"
    ContentType.AddressAuxiliaryDetails -> "addressAuxiliaryDetails"
    ContentType.PostalCodeExtended -> "postalCodeExtended"
    ContentType.PersonFullName -> "personFullName"
    ContentType.PersonFirstName -> "personFirstName"
    ContentType.PersonLastName -> "personLastName"
    ContentType.PersonMiddleName -> "personMiddleName"
    ContentType.PersonMiddleInitial -> "personMiddleInitial"
    ContentType.PersonNamePrefix -> "personNamePrefix"
    ContentType.PersonNameSuffix -> "personNameSuffix"
    ContentType.PhoneNumber -> "phoneNumber"
    ContentType.PhoneNumberDevice -> "phoneNumberDevice"
    ContentType.PhoneCountryCode -> "phoneCountryCode"
    ContentType.PhoneNumberNational -> "phoneNumberNational"
    ContentType.Gender -> "gender"
    ContentType.BirthDateFull -> "birthDateFull"
    ContentType.BirthDateDay -> "birthDateDay"
    ContentType.BirthDateMonth -> "birthDateMonth"
    ContentType.BirthDateYear -> "birthDateYear"
    ContentType.SmsOtpCode -> "smsOtpCode"
    else -> "unknown"
}
