name: Daily CI
on:
  schedule:
    # every day at 8am
    - cron: '0 8 * * *'
jobs:
  end-to-end-tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          # use Java 8 for Locale and Currency compatibility with Android
          java-version: 8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Unit tests
        run: ./gradlew :stripe-test-e2e:testDebugUnitTest
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: unit-test-report
          path: stripe-test-e2e/build/reports/tests/testDebugUnitTest/

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          disable-animations: true
          script: ./gradlew connectedAndroidTest
        env:
          STRIPE_EXAMPLE_BACKEND_URL: ${{ secrets.STRIPE_EXAMPLE_BACKEND_URL }}
          STRIPE_EXAMPLE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_EXAMPLE_PUBLISHABLE_KEY }}

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: instrumentation-test-report
          path: example/build/reports/androidTests/connected/flavors/debugAndroidTest/
