name: End-to-end tests
on:
  schedule:
    # every day at 8am
    - cron: '0 8 * * *'
jobs:
  end-to-end-tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: ./.github/actions/stripe_setup
      - name: End-to-end tests
        env:
          STRIPE_END_TO_END_TESTS_BACKEND_URL: ${{ secrets.STRIPE_END_TO_END_TESTS_BACKEND_URL }}
          STRIPE_END_TO_END_TESTS_PUBLISHABLE_KEY: ${{ secrets.STRIPE_END_TO_END_TESTS_PUBLISHABLE_KEY }}
        run: ./gradlew :stripe-test-e2e:testDebugUnitTest
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: unit-test-report
          path: stripe-test-e2e/build/reports/tests/testDebugUnitTest/
      - name: Notify failure endpoint
        id: notifyFailureEndpoint
        if: failure()
        run: |
          ./scripts/notify_failure_endpoint.rb \
          ${{ secrets.SDK_FAILURE_NOTIFICATION_ENDPOINT }} \
          ${{ secrets.SDK_FAILURE_NOTIFICATION_ENDPOINT_HMAC_KEY }} \
          "https://github.com/stripe/stripe-android/actions/runs/${{ github.run_id }}" \
          RUN_MOBILESDK
