name: financial-connections-example size diff
on:
  pull_request:
    paths:
      - 'financial-connections/**'
      - 'stripe-core/**'
      - 'payments-model/**'
      - 'dependencies.gradle'
jobs:
  # Checkout base branch and build the APK
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - name: Build base branch
        run: ./gradlew :financial-connections-example:assembleRelease && mv financial-connections-example/build/outputs/apk/release/financial-connections-example-release-unsigned.apk financial-connections-example/build/outputs/apk/release/financial-connections-example-release-base.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: financial-connections-example/build/outputs/apk/release/financial-connections-example-release-base.apk

  # Checkout PR branch and build the APK
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build PR branch
        run: ./gradlew :financial-connections-example:assembleRelease && mv financial-connections-example/build/outputs/apk/release/financial-connections-example-release-unsigned.apk financial-connections-example/build/outputs/apk/release/financial-connections-example-release-pr.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: financial-connections-example/build/outputs/apk/release/financial-connections-example-release-pr.apk

  # Execute Diffuse only when the two APKs are built successfully
  diffuse:
    needs: [ build-base, build-pr ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download APKs
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: diffuse
        id: diffuse
        uses: usefulness/diffuse-action@v1
        with:
          old-file-path: apk/financial-connections-example-release-base.apk
          new-file-path: apk/financial-connections-example-release-pr.apk

      # Post comment with output

      - uses: peter-evans/find-comment@v1
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Diffuse output

      - uses: peter-evans/create-or-update-comment@v1
        if: ${{ steps.diffuse.outputs.diff-raw != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            Diffuse output:

            ${{ steps.diffuse.outputs.diff-gh-comment }}
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload diffuse output
        uses: actions/upload-artifact@v2
        with:
          name: diffuse-output
          path: ${{ steps.diffuse.outputs.diff-file }}
