name: financial-connections-pr
on:
  pull_request:
    paths:
      - 'financial-connections/**'
      - 'stripe-core/**'
      - 'payments-model/**'
      - 'dependencies.gradle'
jobs:
  # Use emerge tools to analyze the example app size
  apk-size-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/stripe_setup
      - name: Generate Android release bundle
        run: ./gradlew :financial-connections-example:bundleRelease
      - name: Upload artifact to Emerge
        uses: EmergeTools/emerge-upload-action@v1.0.3
        with:
          artifact_path: financial-connections-example/build/outputs/bundle/release/financial-connections-example-release.aab
          emerge_api_key: ${{ secrets.EMERGE_API_KEY }}
          build_type: release
