name: financial-connections-pr
on:
  pull_request:
jobs:
  # Use emerge tools to analyze the example app size
  apk-size-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/stripe_setup
      - name: Upload release bundle to Emerge
        run: ./gradlew :financial-connections-example:emergeUploadReleaseAab
        env:
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_KEY }}
          EMERGE_TAG: release

