name: CI
on:
  pull_request:
    paths:
      - 'example/build.gradle'
      - '**-example/build.gradle'

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Risky Change
      - uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            Risky Change
            
            This is considered a risky change because it adjusts the sample app build.gradle, please review carefully.
            We've seen issues in the past which resulted in failed builds for consumers. Please make sure the build.gradle change is intended.
            
            [ ] I acknowledge that I'm changing an example app and have verified that the SDK remains in a shippable state.
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
